=== BiemannT/tifo/html/def/Snippet.dtd
<!-- Definition scheme for snippets -->

<!-- Main-Element -->
<!ELEMENT tifo (info, version+)>
    <!ATTLIST tifo
        guid ID #REQUIRED
    >

<!-- General Meta-Information for the snippet -->
<!ELEMENT info (description, structure)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT structure (level1, level2?, level3?, level4?, level5?, level6?, level7?, level8?, level9?)>
    <!ELEMENT level1 (#PCDATA)>
    <!ELEMENT level2 (#PCDATA)>
    <!ELEMENT level3 (#PCDATA)>
    <!ELEMENT level4 (#PCDATA)>
    <!ELEMENT level5 (#PCDATA)>
    <!ELEMENT level6 (#PCDATA)>
    <!ELEMENT level7 (#PCDATA)>
    <!ELEMENT level8 (#PCDATA)>
    <!ELEMENT level9 (#PCDATA)>

<!-- Definition of each version of the snippet -->
<!ELEMENT version (content+)>
<!ATTLIST version
 number CDATA #REQUIRED>

<!-- Content Definition for each version and a specific language--> 
<!ELEMENT content ANY>
<!ATTLIST content
    lang (none | de | en) #REQUIRED
    date CDATA #REQUIRED
    transtate (original | pending | translated) #REQUIRED
>

<!-- Allowable HTML-Elements -->
<!ELEMENT a ANY>
<!ATTLIST a
    id ID #IMPLIED
    class CDATA #IMPLIED
    href CDATA #REQUIRED
    target (_self | _blank | _parent | _top | _unfencedTop) #IMPLIED
>

<!ELEMENT address ANY>
<!ATTLIST address
    id ID #IMPLIED
    class CDATA #IMPLIED
>

<!ELEMENT p ANY>
<!ATTLIST p
    id ID #IMPLIED
    class CDATA #IMPLIED
>

=== BiemannT/tifo/html/Snippets/General_Company Info_Full Address Company A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tifo SYSTEM "../def/Snippet.dtd">
<tifo guid="c6616209-dfb5-4594-bcb2-60b2291682d0">
    <info>
        <description>Full Address Company A</description>
        <structure>
            <level1>General</level1>
            <level2>Company Info</level2>
        </structure>
    </info>
    <version number="1">
        <content lang="de" date="2024-10-18" transtate="original">
            <address>
                <p>Musterfirma GmbH</p>
                <p>Muster Straße 1</p>
                <p>12345 Musterstadt</p>
                <p>Deutschland</p>
                <p>
                    <a href="https://www.musterfirma.de" target="_blank">www.musterfirma.de</a>
                </p>
                <p>
                    <a href="tel:+49.1234.1234.0">Tel: +49 1234 1234-0</a>
                </p>
                <p>
                    <a href="mailto:info@musterfirma.de">Mail: info@musterfirma.de</a>
                </p>
            </address>
        </content>
        <content lang="en" date="2024-10-20" transtate="translated">
            <address>
                <p>Musterfirma GmbH</p>
                <p>Muster Straße 1</p>
                <p>12345 Musterstadt</p>
                <p>Germany</p>
                <p>
                    <a href="https://www.musterfirma.com" target="_blank">www.musterfirma.com</a>
                </p>
                <p>
                    <a href="tel:+49.1234.1234.0">Tel: +49 1234 1234-0</a>
                </p>
                <p>
                    <a href="mailto:info@musterfirma.com">Mail: info@musterfirma.com</a>
                </p>
            </address>
        </content>
    </version>
</tifo>
